files:
  - source: /*.*
    ignore:
      - /*.xml
      - /*.csv
    translation: /translations/%two_letters_code%/%original_file_name%
  - source: /Sample.csv
    translation: /translations/%two_letters_code%/%original_file_name%
    scheme: 'identifier,source_phrase,translation'
  - source: Multilingual_spreadsheet_sample.csv
    translation: /translations/%two_letters_code%/%original_file_name%
    multilingual_spreadsheet: 1
    scheme: 'identifier,context,source_phrase,de,it,max_length'
