"preserve_hierarchy": true
"export_languages" : [
"de"
]
"files": [
  {
  "source" : "/*.*"
  "translation" : "/translations/%two_letters_code%/%original_file_name%"
     "ignore" : [
       "/*.xml"
       ]
    
    "multilingual_spreadsheet": 1
    "first_line_contains_header": true,
    "scheme": "identifier,context,source_phrase,de,it,max_length"
    }
   ]
