#export_languages:                                
#    de
#files:
#  - source: /*.*
 #   ignore:
 #     - /*.csv
 #     - /*.xml
 #   translation: /translations/%two_letters_code%/%original_file_name% 


"files": [
  {
    "source" : "/*.*",                                          
    "translation": /translations/%two_letters_code%/%original_file_name%        
    "ignore":
       "/*.csv",
       "/*.xml"
     "export_languages":                                    
    "de"
    }
]
