files:
  - source: /*.*
    ignore:
      - /*.csv
      - /*.xml
    translation: /translations/%two_letters_code%/%original_file_name%
    translation_replace: &ref_en.
      en.: 
       "languages_mapping" : {
      "two_letters_code" : {
        "it" : ""
       
