export_languages : [
"de"
]

files:
  - source: /*.*
    ignore:
      - /*.xml
    translation: /translation/%two_letters_code%/%original_file_name%
    multilingual_spreadsheet: 1
    scheme: 'identifier,context,source_phrase,de,it,max_length'
