preserve_hierarchy: true
export_languages: de
files:
  - source: /*.*
    ignore:
      - /*.xml
    translation: /translations/%two_letters_code%/%original_file_name%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,de,it,max_length'
   
